### ISSUE TITLE
Configurations without version are not supported by #config= URL styles.

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/web-confdb#15]
Configurations without version are not supported by #config= URL styles.
For example, this

https://cmsweb.cern.ch/confdb/#config=/dev/CMSSW_7_5_0/HLT

results in the message "The URL is not correct, please try again."

**Comment by vinnie87** [comment]
Done, under testing

**Comment by vinnie87** [comment]
Deployed in v1.3.8
