### ISSUE TITLE
some menus show multiple copies of the same path in a dataset

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/web-confdb#27]
In some menus, like [/cdaq/special/QuietBeams/v1.0.2/HLT/V1](https://cmsweb.cern.ch/confdb/#config=/cdaq/special/QuietBeams/v1.0.2/HLT/V1), the Summary view shows the same path muliple times in a given dataset: ![summary_view](https://cloud.githubusercontent.com/assets/4069793/14679866/f3553856-071b-11e6-9ae9-1b6e0744d49c.png)

**Comment by vinnie87** [comment]
The bug's origin has been detected, is going to be fixed.

**Comment by vinnie87** [comment]
The bug has been fixed. Going to production.
