### ISSUE TITLE
the prescales shown in the Summary view should take into account the prescale of the EndPath

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/web-confdb#28]
The Summary view currently shows, for each path in each stream, the product of the prescale for the path and the "smart prescale" for that path in the endpath corresponding to the stream.

It should take into account also the prescale of the endpath corresponding to the stream.

**Comment by vinnie87** [comment]
Developed, under testing.

**Comment by vinnie87** [comment]
Deployed in v1.3.8
