### ISSUE TITLE
HLT menus in 2016 use a different module for the L1 decision

### ISSUE THREAD

**Issue by fwyzard** [cms-sw/web-confdb#29]
HLT menus for the 2016 data taking use a different module for the L1 trigger decision: `HLTL1TSeed` is used instead of `HLTLevel1GTSeed`.

The actual expression is still in the `string` parameter `L1SeedsLogicalExpression`.

**Comment by vinnie87** [comment]
Developed. Under testing.

**Comment by vinnie87** [comment]
Deployed in v1.3.8
