### ISSUE TITLE
Missing sequence in path in web gui

### ISSUE THREAD

**Issue by BenjaminRS** [cms-sw/web-confdb#39]
Hi - when looking at (for example): https://cmsweb.cern.ch/confdb/#config=/online/collisions/2016/25ns15e33/v4.0/HLT/V2
and in details view, at the path: HLT_DoubleMu3_PFMET50_v3
Under: process.HLTL2muonrecoSequence
it appears that a sequence is missing: process.HLTL2muonrecoNocandSequence
(see attached picture)
When downloading the python file, I can see that the sequence is there for the path. Also in the web gui I see the sequence there for other paths, such as HLT_Mu50_v4.

![doublemu3sequence](https://cloud.githubusercontent.com/assets/5666560/18507456/c897854c-7a70-11e6-9861-304c59f75ffb.png)

**Comment by vinnie87** [comment]
Hi,
So the sequence should be there but it does not appear, is it correct?

**Comment by BenjaminRS** [comment]
Hi. The sequence is there, but you cannot see it in the GUI for that path. It can be seen if you download the python configuration and look at it, or look at other paths which have the same parent sequence (HLTL2muonrecoSequence).

**Comment by vinnie87** [comment]
Ok, so it looks like the problem is only on that path, is that correct?

**Comment by BenjaminRS** [comment]
Not sure which paths are affected, just quickly trying a couple others I find also:
HLT_DoubleMu8_Mass8_PFHT250_v4

**Comment by BenjaminRS** [comment]
Then in an odd way: HLT_DoubleMu8_Mass8_PFHT300_v7 has 2 lots of HLTL2muonrecoNocandSequence ...

**Comment by vinnie87** [comment]
Not asking to check, but do you know if this behavior happens also for other menu or you saw it just for this one?

**Comment by BenjaminRS** [comment]
This is the first time we notice it (but havent checked in other menus)

**Comment by vinnie87** [comment]
OK. It is the first time I see something like that, I'm looking into it.
Please, if you notice similar behavior (I do not know well any menu - besides some reference ones) let me know.

**Comment by vinnie87** [comment]
Hi,
Spotted the bug, going to fix.

**Comment by vinnie87** [comment]
Hi @BenjaminRS , I have a possible fix for the bug (more complex than expected),
can you have a look with me to a couple of Paths, from my pc, in order to validate the fix?

Thanks.

**Comment by BenjaminRS** [comment]
Hi @vinnie87 sure, I will email you offline from here.

**Comment by BenjaminRS** [comment]
Hi @vinnie87 using the test fix with menu /online/collisions/2016/25ns15e33/v4.0/HLT/V2 I looked at:
HLT_DoubleMu3_PFMET50_v3
HLT_DoubleMu8_Mass8_PFHT250_v4
HLT_DoubleMu8_Mass8_PFHT300_v7
HLT_IsoMu27_v5

And everything looked to be correct. I then looked at another menu (/frozen/2016/25ns15e33/v4.1/HLT/V3) and quickly went through various other muon paths but everything looked fine there as well.

Many thanks for solving this bug!
Benjamin

**Comment by vinnie87** [comment]
Hi,
Good. Going to production in the next available CMSWEB release.
