### ISSUE TITLE
bidict license compliance

### ISSUE THREAD

**Issue by jab** [cms-sw/web-confdb#42]
I am the author of [bidict](https://github.com/jab/bidict). One of the conditions of bidict's [license](https://github.com/jab/bidict/tree/master/LICENSE) is that you must include a copy of the license and copyright notice along with the code.¹

It looks like this project is [including bidict's code](https://github.com/cms-sw/web-confdb/tree/master/Application/external/bidict) without a copy of its license, in violation of the license. Could you please fix that?

While you're at it, you may also be interested in upgrading to the latest version, v0.15.0, which includes significant [performance improvements](https://bidict.readthedocs.io/en/v0.15.0/changelog.html), and is recommended for all users.

I'm very happy to see that bidict has been useful to developers at CERN!

[1] https://choosealicense.com/licenses/mpl-2.0/

**Comment by fwyzard** [comment]
Hi @jab,
apology for forgetting to include a copy of bidict's LICENSE along with the sources.

To minimise the impact, I'm keeping the current version from November 2015 and just adding the LICENSE as of that date (i.e. https://github.com/jab/bidict/blob/7d8ae827c492eedc7d9400886be21718d6db6d0b/LICENSE).

I'll open an issue to remember to check the latest code and license.

Thank you for sharing your work !

**Comment by fwyzard** [comment]
Fixed by #43 .

**Comment by jab** [comment]
Thanks for fixing!

By the way, I quickly searched through this repo and I believe you can upgrade to the latest bidict release without breaking any of your call sites. [1]

Besides the performance improvements I mentioned, there have also been several bugfixes since the version you imported from 2015. Details can be found in https://bidict.readthedocs.io/changelog.html.

[1] It looks like `.inv` is the only bidict API [you're using](https://github.com/cms-sw/web-confdb/blob/master/Application/utils.py). That API has been stable since the [very first commit](https://bitbucket.org/jab/bidict/commits/00db45f0fc52cd5f2daabba9a146541483fa8529) almost 10 years ago, and won't be going anywhere. That said, if you hit any expected issues, please don't hesitate to let me know, and I'll be happy to try to help.
